#![cfg_attr(not(feature = "proc-macro2-diagnostics"), no_std)]

extern crate alloc;

use alloc::string::String;

#[cfg(feature = "proc-macro2-diagnostics")]
use proc_macro2::Span;
#[cfg(feature = "proc-macro2-diagnostics")]
use proc_macro2_diagnostics::Diagnostic;

#[cfg(feature = "proc-macro2-diagnostics")]
pub type MacroResult<T> = Result<T, Diagnostic>;

pub type MacroDeepResult<T> = Result<T, DeepDiagnostic>;

#[derive(Clone, Debug)]
pub struct DeepDiagnostic {
    #[cfg(feature = "proc-macro2-diagnostics")]
    level: proc_macro2_diagnostics::Level,

    message: String,
}
impl DeepDiagnostic {
    // @TODO macro_rules and also generate: pub fn warning, note, help
    pub fn error<T: Into<String>>(message: T) -> Self {
        Self {
            #[cfg(feature = "proc-macro2-diagnostics")]
            level: proc_macro2_diagnostics::Level::Error,

            message: message.into(),
        }
    }

    pub fn message(&self) -> &str {
        &self.message
    }

    // @TODO if implemented in proc_macro2_diagnostics, make it accept MultiSpan:
    //
    // pub fn spanned<S: MultiSpan>(self, s: S) -> Diagnostic
    #[cfg(feature = "proc-macro2-diagnostics")]
    pub fn spanned(self, span: Span) -> Diagnostic {
        Diagnostic::spanned(span, self.level, self.message)
    }
}
impl From<DeepDiagnostic> for String {
    fn from(deep: DeepDiagnostic) -> Self {
        deep.message
    }
}

pub mod ext {
    #[cfg(feature = "proc-macro2-diagnostics")]
    use crate::MacroResult;
    use crate::{sealed, DeepDiagnostic, MacroDeepResult};

    use alloc::format;
    use alloc::string::{String, ToString};
    use core::fmt::Debug;

    #[cfg(feature = "proc-macro2-diagnostics")]
    use proc_macro2::Span;
    #[cfg(feature = "proc-macro2-diagnostics")]
    use proc_macro2_diagnostics::{Diagnostic, SpanDiagnosticExt as _};

    #[cfg(feature = "proc-macro2-diagnostics")]
    pub trait MacroDeepResultExt<T>: sealed::Trait {
        // @TODO if implemented in proc_macro2_diagnostics, make it accept MultiSpan.
        /// Add the given [Span], and transform to [MacroResult].
        fn spanned(self, span: Span) -> MacroResult<T>;
    }
    #[cfg(feature = "proc-macro2-diagnostics")]
    impl<T> MacroDeepResultExt<T> for MacroDeepResult<T> {
        fn spanned(self, span: Span) -> MacroResult<T> {
            self.map_err(|deep_err| deep_err.spanned(span))
        }
    }
    impl<T> sealed::Trait for MacroDeepResult<T> {
        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait IntoStringExt: Into<String> {
        fn into_error(self) -> DeepDiagnostic;
        /// Param `f` is a closure/function that returns a [String]. This method returns
        /// [DeepDiagnostic] that [String], with a space appended, and ONLY THEN [String]
        /// generated by `self.into()`.
        ///
        /// We do NOT need alternative methods that would save allocating a [String], like `fn
        /// into_error_with_str(self, &str)`, because errors, and especially proc macro errors,
        /// are on a cold execution path.
        fn into_error_with<F: Fn() -> String>(self, f: F) -> DeepDiagnostic;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn into_error_for(self, span: Span) -> Diagnostic;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn into_error_with_for<F: Fn() -> String>(self, f: F, span: Span) -> Diagnostic;

        // Sealing is not really necessary, because we have a blanket impl that covers any and
        // all eligible types, so no other types can implement this trait.
        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T: Into<String>> IntoStringExt for T {
        fn into_error(self) -> DeepDiagnostic {
            DeepDiagnostic::error(self.into())
        }
        fn into_error_with<F: Fn() -> String>(self, f: F) -> DeepDiagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&self.into());
            DeepDiagnostic::error(s)
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn into_error_for(self, span: Span) -> Diagnostic {
            span.error(self)
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn into_error_with_for<F: Fn() -> String>(self, f: F, span: Span) -> Diagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&self.into());
            span.error(s)
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait IntoStringResultExt<T> {
        fn map_error_into(self) -> MacroDeepResult<T>;
        fn map_error_into_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T>;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_into_for(self, span: Span) -> MacroResult<T>;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_into_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T>;

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T, E: Into<String>> IntoStringResultExt<T> for Result<T, E> {
        fn map_error_into(self) -> MacroDeepResult<T> {
            self.map_err(|e| DeepDiagnostic::error(e))
        }
        fn map_error_into_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&e.into());
                DeepDiagnostic::error(s)
            })
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_into_for(self, span: Span) -> MacroResult<T> {
            self.map_err(|e| span.error(e))
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_into_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&e.into());
                span.error(s)
            })
        }
        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait OptionOrBoolExt<T> {
        fn ok_or_error<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T>;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn ok_or_error_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T>;

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T> OptionOrBoolExt<T> for Option<T> {
        fn ok_or_error<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T> {
            self.ok_or_else(|| DeepDiagnostic::error(f()))
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn ok_or_error_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T> {
            self.ok_or_else(|| span.error(f()))
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }
    impl OptionOrBoolExt<()> for bool {
        fn ok_or_error<F: Fn() -> String>(self, f: F) -> MacroDeepResult<()> {
            // bool::ok_or_else is unstable: https://github.com/rust-lang/rust/issues/142748
            if self {
                Ok(())
            } else {
                Err(DeepDiagnostic::error(f()))
            }
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn ok_or_error_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<()> {
            if self {
                Ok(())
            } else {
                Err(span.error(f()))
            }
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait ToStringExt: ToString {
        fn to_error(&self) -> DeepDiagnostic;
        fn to_error_with<F: Fn() -> String>(&self, f: F) -> DeepDiagnostic;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn to_error_for(&self, span: Span) -> Diagnostic;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn to_error_with_for<F: Fn() -> String>(&self, f: F, span: Span) -> Diagnostic;

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T: ToString> ToStringExt for T {
        fn to_error(&self) -> DeepDiagnostic {
            DeepDiagnostic::error(self.to_string())
        }
        fn to_error_with<F: Fn() -> String>(&self, f: F) -> DeepDiagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&self.to_string());
            DeepDiagnostic::error(s)
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn to_error_for(&self, span: Span) -> Diagnostic {
            span.error(self.to_string())
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn to_error_with_for<F: Fn() -> String>(&self, f: F, span: Span) -> Diagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&self.to_string());
            span.error(s)
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait ToStringResultExt<T> {
        fn map_error_to(self) -> MacroDeepResult<T>;
        fn map_error_to_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T>;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_to_for(self, span: Span) -> MacroResult<T>;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_to_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T>;

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T, E: ToString> ToStringResultExt<T> for Result<T, E> {
        fn map_error_to(self) -> MacroDeepResult<T> {
            self.map_err(|e| DeepDiagnostic::error(e.to_string()))
        }
        fn map_error_to_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&e.to_string());
                DeepDiagnostic::error(s)
            })
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_to_for(self, span: Span) -> MacroResult<T> {
            self.map_err(|e| span.error(e.to_string()))
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_to_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&e.to_string());
                span.error(s)
            })
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait DebugExt: Debug {
        fn dbg_error(&self) -> DeepDiagnostic;
        fn dbg_error_with<F: Fn() -> String>(self, f: F) -> DeepDiagnostic;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn dbg_error_for(&self, span: Span) -> Diagnostic;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn dbg_error_with_for<F: Fn() -> String>(self, f: F, span: Span) -> Diagnostic;
        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }

    impl<T: Debug> DebugExt for T {
        fn dbg_error(&self) -> DeepDiagnostic {
            DeepDiagnostic::error(format!("{self:?}"))
        }
        fn dbg_error_with<F: Fn() -> String>(self, f: F) -> DeepDiagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&format!("{self:?}"));
            DeepDiagnostic::error(s)
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn dbg_error_for(&self, span: Span) -> Diagnostic {
            span.error(format!("{self:?}"))
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn dbg_error_with_for<F: Fn() -> String>(self, f: F, span: Span) -> Diagnostic {
            let mut s = f();
            s.push(' ');
            s.push_str(&format!("{self:?}"));
            span.error(s)
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }

    pub trait DbgResultExt<T> {
        fn map_error_dbg(self) -> MacroDeepResult<T>;
        fn map_error_dbg_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T>;

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_dbg_for(self, span: Span) -> MacroResult<T>;
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_dbg_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T>;

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam);
    }
    impl<T, E: Debug> DbgResultExt<T> for Result<T, E> {
        fn map_error_dbg(self) -> MacroDeepResult<T> {
            self.map_err(|e| DeepDiagnostic::error(format!("{e:?}")))
        }
        fn map_error_dbg_with<F: Fn() -> String>(self, f: F) -> MacroDeepResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&format!("{e:?}"));
                DeepDiagnostic::error(s)
            })
        }

        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_dbg_for(self, span: Span) -> MacroResult<T> {
            self.map_err(|e| span.error(format!("{e:?}")))
        }
        #[cfg(feature = "proc-macro2-diagnostics")]
        fn map_error_dbg_with_for<F: Fn() -> String>(self, f: F, span: Span) -> MacroResult<T> {
            self.map_err(|e| {
                let mut s = f();
                s.push(' ');
                s.push_str(&format!("{e:?}"));
                span.error(s)
            })
        }

        #[allow(private_interfaces)]
        fn _seal(&self, _: &sealed::TraitParam) {}
    }
}

pub mod assert {
    use crate::ext::OptionOrBoolExt;
    use crate::MacroDeepResult;
    #[cfg(feature = "proc-macro2-diagnostics")]
    use crate::MacroResult;

    use alloc::string::String;
    #[cfg(feature = "proc-macro2-diagnostics")]
    use proc_macro2::Span;

    pub fn true_or_error<F: Fn() -> String>(b: bool, f: F) -> MacroDeepResult<()> {
        b.ok_or_error(f)
    }
    #[cfg(feature = "proc-macro2-diagnostics")]
    pub fn true_or_error_for<F: Fn() -> String>(b: bool, f: F, span: Span) -> MacroResult<()> {
        b.ok_or_error_for(f, span)
    }
}

pub mod sealed {
    /// Intentionally NOT public.
    pub(crate) struct TraitParam;
    pub trait Trait {
        #[allow(private_interfaces)]
        fn _seal(&self, _: &TraitParam);
    }
}
